# Generated by Django 4.2.7 on 2024-02-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commnet',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commnet',
            name='name',
        ),
        migrations.AddField(
            model_name='commnet',
            name='review',
            field=models.CharField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=10, null=True),
        ),
    ]
