# Generated by Django 4.2.7 on 2024-02-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='blog',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
    ]
